# Database Configuration
database:
  host: ""
  port: ""
  db-name: ""
  user: ""
  password: ""

# Pool Connections Configuration
pool:
  max-size: 10
  idle-timeout: 30000

discord:
  bot-token: "YOUR_TOKEN_HERE"
  server-id: "YOUR_GUILD_ID_HERE"
  channels:
    logs: "CHANNEL_LOGS_ID_HERE"